### ISSUE TITLE
Can you provide the examples for using your lib to insert the data

### ISSUE THREAD

**Issue by myereach** [davidB/metrics-influxdb#14]
Dear Sir,
I like your lib but I can not find the example for inserting data to influxDB and can you please kindly provide one. I did use it to import data from mysql to influxDB but I am not sure I use the resetRequest() correctly.
Also, because I have a billion data need to insert to influxDB and do you have any recommend way to using your lib to do this . bulk insert maybe
Thanks in advance

Richard Huang

**Comment by davidB** [comment]
Hi,

If you send your own data, I suppose you don't use the metrics part of the lib. But you can look at the source of [InfluxdbReporter.java](src/main/java/metrics_influxdb/InfluxdbReporter.java) mainly the [report](src/main/java/metrics_influxdb/InfluxdbReporter.java#L263) method.

```
influxdb.resetRequest();
// fill a bulk of data via influxdb.appendSeries(...) x n times
influxdb.sendRequest(true, false);
```
I have no recommendation about the size of the bulk.

Is it clear ?

**Comment by myereach** [comment]
Thanks for your response. According to the  InfluxdbReporter.java, it seems before I call the appendSeries() method, I always need to call the resetRequest() even the initial one. Is it correct? 
I dont understand why you said "If you send your own data, I suppose you don't use the metrics part of the lib" and can you please explain it for me. Thanks
I did write a program fetch the TS data from mysql and use your InfluxdbHttp class to build the json and send it to the influxDB.

**Comment by davidB** [comment]
"If you send your own data, I suppose you don't use the metrics part of the
lib" means  "I suppose you don't use InfluxdbReporter or
com.codahale.metrics.*"

yes resetRequest()is to clear, it's not mandatory to call it the first time
but it's avoid to create a special rules for the first bulk.

**Comment by davidB** [comment]
resetRequest()is to clear and initialize data, it's MANDATORY to call it (include the first time).

 I wrote a wrong response  previously.

**Comment by myereach** [comment]
Yes, I read your code and resetRequest() is also to initialize data ( put the magic '[' )
Without it, it can not work I spent half hour debug it and figure it out. Thanks for you information and I think I am on the right track. If I might make a suggestion you maybe need put this leading '[' in the JsonBuilderDefault.toJsonString(), that might be more intuitivel
Thanks for you help
