### ISSUE TITLE
Add support for influxdb v0.9

### ISSUE THREAD

**Issue by leelasharma** [davidB/metrics-influxdb#18]
Influxdb's new version has a different API http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html

**Comment by davidB** [comment]
Can you made a Pull Request ? I don't have time to update it nearly

**Comment by mje113** [comment]
+1 I'll try to attempt a PR if no one else has already started the effort.

**Comment by kiview** [comment]
Any news on this? Someone already started working on it?

**Comment by McFoggy** [comment]
@davidB and others, I started to work a bit on this issue [here](https://github.com/McFoggy/metrics-influxdb/tree/issue-18) as #20 might not correspond to what I would expect.
But before going further I would like some discussions/answers to the following questions:
- do we want to keep API compatibility with existing InfluxdbReporter, InfluxdbReporter.Builder & Influxdb?
- if no can we just drop and replace obsolete stuff or do we keep the old stuff apart from the new one?

**Comment by davidB** [comment]
> do we want to keep API compatibility with existing InfluxdbReporter,
InfluxdbReporter.Builder & Influxdb?

If possible yes. What do you want to change ?

> if no can we just drop and replace obsolete stuff or do we keep the old
stuff apart from the new one?

Keeping the old stuff could be managed via version + branch or by using an
other package name for new code. As you don target "drop-in" update.

**Comment by McFoggy** [comment]
@davidB thanks for quick reply

I'll do my best to keep things compatible but as all concepts in Influxdb have changed in v09, especially tags+measure compared to previous metric-name, I think we cannot hide this change, or at least we have to expose new feature especially some transformations `metric-name => [measure, tags]`

**Comment by davidB** [comment]
As you upgrade the version to 0.7 on your fork, I fine with small API
change. I also agree to to not hide influxdb concept.

**Comment by McFoggy** [comment]
@davidB can you please clarify the java target version of the library for a 0.7.X version
- metrics-core 3.1.0 is java 6 compliant
- the metrics-influxdb pom states java 7
- the code itself is already java 8 (usage of Double.isFinite in JSonBuilder)

**Comment by davidB** [comment]
java 1.8 (java 1.7 EOL in  2016)

**Comment by McFoggy** [comment]
cool , thanks

**Comment by McFoggy** [comment]
@all see PR #26 for influxdb v09 support
