### ISSUE TITLE
naming of metric values is not consistent with other Reporters

### ISSUE THREAD

**Issue by McFoggy** [davidB/metrics-influxdb#27]
If we look at some standard metrics reporters (CSV, graphite, ganglia, ...), the naming of values is different than the one in `metrics-influxdb`

For example histogram values in standard reporters: `count,max,mean,min,stddev,p50,p75,p95,p98,p99,p999`
in InfluxDBReporter
`run-count,max,mean,min,std-dev,50-percentile,75-percentile,95-percentile,99-percentile,999-percentile`.

It is even worst for `count` as in InfluxDBReporter it is the number of samples in the Snapshot instead of the metric calls.

I would propose to correct this by default and to introduce a backward compatible setting via the builder.

**Comment by davidB** [comment]
no news, feel free to make PR
