### ISSUE TITLE
integrate with CI

### ISSUE THREAD

**Issue by McFoggy** [davidB/metrics-influxdb#28]
would be great to see this lib integrated with a CI plateform.

[Travis-ci](https://travis-ci.org) is a popular one for github project ; as easy as pushing a `.travis.yml` file at the root of the project which conatins for example:

```
language: java
jdk:
  - oraclejdk8
```

It is enough to at least receive some compile & test feedback for each commit and pull-request.

**Comment by davidB** [comment]
IMHO the lib is too small to need a CI (in term of code size, team size and
update frequency).

**Comment by McFoggy** [comment]
As the library maintainer you probably know better then I do how much time it costs you to tests PR.
In my strict personal opinion, adding one file of 3 lines, already helps a lot and is valuable in order to have a feedback on any PR that comes in.

**Comment by davidB** [comment]
DONE
