### ISSUE TITLE
BoundedFIFO.add to delegate (LinkedBlockingQueue) throws exception

### ISSUE THREAD

**Issue by roiaddi** [davidB/metrics-influxdb#32]
in BoundedFIFO.add() function, one check if add succeeded in a while loop.
if insert succeeded this.delegate.add(e) will return true, but in case it won't it will throws IllegalStateException: "Queue full".
add function on LinkedBlockingQueue will always return true or throw an exception (never return false)

**Comment by davidB** [comment]
we replace add by offer

**Comment by pavelkokush** [comment]
I am getting this error "Queue full" in BoundedFIFO.add() sometimes (0.8.2 version). Seems that with new implementation of BoundedFIFO.add() I will lose some metrics silently? It might be some very small amount of metrics, but probably it can be some big amount also.
