### ISSUE TITLE
Timestamp precision for InfluxDB v0.9

### ISSUE THREAD

**Issue by ShijunK** [davidB/metrics-influxdb#35]
InfluxDB v0.9 expect timestamp in nanoseconds epoch time by default, instead of milliseconds as in v0.8. 

The reporter builder and measure provide default clock from Metrics lib, which report time in milliseconds. The issue can be work around by providing a customized clock, which override Clock#getTime() to report in nanoseconds. However, it might be better to add a precision field to reporter and measure, set it default to nanoseconds for v0.9.

**Comment by davidB** [comment]
In master, the precision is defined to ms in the request.

see https://github.com/davidB/metrics-influxdb/commit/5ebd76a923dd749f0e9bba6d03ee1f03b972f3f9

**Comment by ShijunK** [comment]
I am talking about Line protocal: https://github.com/davidB/metrics-influxdb/blob/master/src/main/java/metrics_influxdb/serialization/line/Inliner.java

**Comment by johnrengelman** [comment]
Agreed, the UDP Line protocol does not work with InfluxDB 0.9+

the timestamp sent in the message must be in nanoseconds since epoch

**Comment by davidB** [comment]
should be fixed with https://github.com/davidB/metrics-influxdb/commit/6e6b2865ce4fa8f5688dc258e8b28c0fd21e3fd3
