### ISSUE TITLE
Unable to use jitpack repo configuration in transitive dependency

### ISSUE THREAD

**Issue by wakandan** [davidB/metrics-influxdb#37]
We have this package in a 'core' project that other projects depend on. When we were still using `net.alchim31:metrics-influxdb:0.7.0`, the dependency is downloaded from maven so it's pretty convenient for us. However since the change to this package and `jitpack` repo, what happened was the 'core' project can be built just fine, however all projects depend on it, and in turn all projects depend on those projects also can't be built. This is real problem because the total number of projects (including transitive ones) are ~ 300 repos. 

Is it possible to publish this package to maven central? Thanks.

**Comment by davidB** [comment]
Hi,

Maven Central or JCenter only accept fixed version. the last fixed version is still 0.7.0. Next release should be deployed on Maven Central/JCenter under the new groupId com.github.davidb. The current SNAPSHOT seems to have bugs, so I can't release it as is.

Until that, I guess a workaround should be to add the jitpack.io repo into your pom (repositories list  are not transitive) or if you use a proxy artifact server (artifactory, nexus), then include jitpack.io in an unified proxy repo.

**Comment by wakandan** [comment]
Hi, it's not really possible to include the `jitpack.io` into the pom because there are too many repo (~300). Changing all of them would be a real pain. Also it doesn't make sense because the down stream repos are not related to what the package is doing functionally. The hierarchy was setup like that, not much can be done about it either...

**Comment by davidB** [comment]
:-(

do you share a parent pom (I guess you use maven).

**Comment by davidB** [comment]
the version 0.8.2 is available in maven central and jcenter repository.
the wip 0.9.x version will introduce api break with version 0.8.x
