### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by shanielh** [davidB/metrics-influxdb#39]
Hi.

Since telegraf now supports listening to "influx-db protocol" in tcp (https://github.com/influxdata/telegraf/issues/481) - I would like to send the data to telegraf in tcp.

Tell me if you like the idea, I can create the PR by myself.

**Comment by davidB** [comment]
I like the idea, but as I'm refactoring the code. I suggest you to wait one week, I'should finish the refactor next week-end.

**Comment by shanielh** [comment]
Great.

**Comment by shanielh** [comment]
@davidB Are you done with the refactor?

**Comment by davidB** [comment]
Not fully, but I already push some of the change, so you can start, if you
wish.
