### ISSUE TITLE
missing maven central deployment

### ISSUE THREAD

**Issue by McFoggy** [davidB/metrics-influxdb#40]
I think no version was published to maven central since you changed the project group.
Please consider pushing the project again to central.

**Comment by davidB** [comment]
I have to adjust the build process I forgot the javadoc jar. today the
artifact is available in jcentral. I'll publish a version 0.8.1 later this
week. and a version 0.9.0 in one or 2 weeks (mainly a refactor of 0.8 with
some api change).

**Comment by McFoggy** [comment]
@davidB is "JCentral" synchronized with maven central and all its replicas?

**Comment by davidB** [comment]
jcenter includes maven central, but maven central doesn't include jcenter.

v0.8.2 should be available on maven central.

**Comment by McFoggy** [comment]
@davidB  Thanks a lot ; artifact can be correctly found in central again.
