### ISSUE TITLE
Allow the ScheduledExecutorService used by InfluxdbReporter to be customized

### ISSUE THREAD

**Issue by ekuefler** [davidB/metrics-influxdb#41]
InfluxdbReporter's builder has a lot of customization options, but it doesn't appear possible to set the ScheduledExecutorService that gets used under the hood. I need the ability to provide my own executor here since my application requires some custom logic to be run whenever threads are instantiated.

**Comment by davidB** [comment]
InfluxdbReporter doesn't create or interact with an Executor. You should take a look into metrics api.

**Comment by ekuefler** [comment]
That's the problem - if I'm reading the code correctly, it looks like InfluxdbReporter implicitly uses an API that creates an Executor, and doesn't expose an API to customize it. It does so through this path:

* [InfluxdbReporter.java:224](https://github.com/davidB/metrics-influxdb/blob/master/src/main/java/metrics_influxdb/InfluxdbReporter.java#L224) creates a MeasurementReporter
* [MeasurementReporter.java:28](https://github.com/davidB/metrics-influxdb/blob/master/src/main/java/metrics_influxdb/measurements/MeasurementReporter.java#L28) calls into SkipIdleReporter's constructor
* [SkipIdleReporter.java:22](https://github.com/davidB/metrics-influxdb/blob/master/src/main/java/metrics_influxdb/SkipIdleReporter.java#L22) calls into ScheduledReporter's constructor which doesn't take an executor
* [ScheduledReporter.java:73](https://github.com/dropwizard/metrics/blob/3.1-maintenance/metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java#L73) constructs a default executor and passes it to another constructor

There's no way to configure the executor after it's been created in ScheduledReporter, so for this to work I'd have to pass my executor to InfluxdbReporter's builder, which would need to pass it up through the constructor chain to avoid invoking the ScheduledReporter constructor that uses the hard-coded executor.

**Comment by davidB** [comment]
More refactor to come (possible breaking API)

**Comment by ekuefler** [comment]
Very cool, thank you!
