### ISSUE TITLE
Release 0.8.3?

### ISSUE THREAD

**Issue by ekuefler** [davidB/metrics-influxdb#51]
Is there a timeline for this? There are several commits since 0.8.2 that I'd like to be able to use.

Thanks!

**Comment by davidB** [comment]
The next version will be 0.9.0 (API change).
no time line, may be next week.

**Comment by ekuefler** [comment]
Works for me, looking forward to it!

**Comment by emanuelez** [comment]
👍 for a new release :)

**Comment by davidB** [comment]
done
