### ISSUE TITLE
Could Support JDK1.7?

### ISSUE THREAD

**Issue by huiwq1990** [davidB/metrics-influxdb#54]
Hi:
   The project use jdk8, but our project use jdk1.7. Could you release the bytecode support jdk7?
   Thank you!

**Comment by davidB** [comment]
IIRC, today, the code also use few feature of the jdk8 api.
jdk7 is EOL. I could take a quick look to estimate the work but I don't
don't know when.

**Comment by emanuelez** [comment]
I was trying to use this library to create the InfluxDB version of this plugin: https://wiki.jenkins-ci.org/display/JENKINS/Metrics+Graphite+Plugin
Jenkins is still using Jenkins 1.7 (and so do lots of legacy codebases I'm sure) so a 1.7 compatible version would be great!

**Comment by emanuelez** [comment]
A quick look at the code shows that only one tiny part of the code uses Java 8 and that would be trivial to fix. The problem seems mostly to be in the unit tests.
